name: polar_example
description: Demonstrates how to use the polar plugin.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  polar:
    path: ../

  uuid: ^4.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  rexios_lints: ^7.0.0

flutter:
  uses-material-design: true
