name: polar
description: This is a Dart plugin wrapper for the Polar SDK on Android and iOS
version: 7.2.0
homepage: https://github.com/Rexios80/polar

environment:
  sdk: ^3.0.0
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.5
  permission_handler: ^11.0.0
  device_info_plus: ^10.0.1
  recase: ^4.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^7.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  uuid: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.polar
        pluginClass: PolarPlugin
      ios:
        pluginClass: PolarPlugin
