name: Analyze
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-cache-
      - name: Pub get
        run: flutter pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos .

  analyze-swift:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install swift-format
        run: brew install swift-format
      - name: Lint
        run: swift-format lint -rs ios
      - name: Format
        run: swift-format -ri ios
      - name: Exit if changed
        run: git diff --exit-code

  analyze-kotlin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ktlint
        run: brew install ktlint
      - name: Format
        run: ktlint android

  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-cache-
      - name: Pub get
        run: flutter pub get
      - name: Package scan
        run: |
          dart pub global activate pana
          pana --exit-code-threshold 0

  build-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-cache-
      - name: Pub get
        run: flutter pub get
      - name: Build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Exit if changed
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Pub cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: pub-cache-
      - name: Pub get
        run: flutter pub get
      - name: Test
        run: flutter test
